# Generated by Django 4.2 on 2023-08-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ObjectOfDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('opinion', models.FloatField(default=0.38)),
                ('attitude', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Unnamed', max_length=100, null=True)),
                ('version', models.CharField(blank=True, default='1.0', max_length=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.simulation')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attitude', models.FloatField(default=0.78)),
                ('opinion', models.FloatField(default=-0.58)),
                ('uncertainty', models.FloatField(default=0.02)),
                ('public_compliance_thresh', models.FloatField(default=0.6)),
                ('private_acceptance_thresh', models.FloatField(default=0.19)),
                ('agent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lyra.agent')),
                ('ood', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lyra.objectofdiscussion')),
                ('topic', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lyra.topic')),
            ],
            options={
                'ordering': ('agent', 'ood', 'topic', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SimAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_type', models.CharField(max_length=50)),
                ('data', models.JSONField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.simulation')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='RunAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_type', models.CharField(max_length=50)),
                ('data', models.JSONField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.run')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='run',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.simulation'),
        ),
        migrations.AddField(
            model_name='objectofdiscussion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.topic'),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('discussion_time', models.IntegerField()),
                ('participants', models.ManyToManyField(to='Lyra.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.run'),
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.CheckConstraint(check=models.Q(('ood__isnull', False), ('topic__isnull', False), _connector='OR'), name='view_ood_or_topic_not_null'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('simulation', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='run',
            unique_together={('simulation', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='objectofdiscussion',
            unique_together={('topic', 'title')},
        ),
    ]
