# Generated by Django 4.2 on 2023-05-03 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('attitude', models.FloatField()),
                ('opinion', models.FloatField()),
                ('uncertainty', models.FloatField()),
                ('public_compliance_thresh', models.IntegerField()),
                ('private_acceptance_thresh', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.agent')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=400)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.simulation')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('discussion_time', models.IntegerField()),
                ('participants', models.ManyToManyField(to='Lyra.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='simRun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.simulationrun'),
        ),
    ]
