# Generated by Django 4.2 on 2023-07-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectofdiscussion',
            name='attitude',
            field=models.FloatField(default=0.96),
        ),
        migrations.AddField(
            model_name='objectofdiscussion',
            name='opinion',
            field=models.FloatField(default=-0.15),
        ),
        migrations.AlterField(
            model_name='view',
            name='attitude',
            field=models.FloatField(default=0.82),
        ),
        migrations.AlterField(
            model_name='view',
            name='opinion',
            field=models.FloatField(default=-0.45),
        ),
        migrations.AlterField(
            model_name='view',
            name='private_acceptance_thresh',
            field=models.FloatField(default=0.22),
        ),
        migrations.AlterField(
            model_name='view',
            name='uncertainty',
            field=models.FloatField(default=0.38),
        ),
    ]
