# Generated by Django 4.2 on 2023-07-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectofdiscussion',
            name='opinion',
            field=models.FloatField(default=-0.64),
        ),
        migrations.AlterField(
            model_name='view',
            name='attitude',
            field=models.FloatField(default=-0.03),
        ),
        migrations.AlterField(
            model_name='view',
            name='opinion',
            field=models.FloatField(default=-0.23),
        ),
        migrations.AlterField(
            model_name='view',
            name='private_acceptance_thresh',
            field=models.FloatField(default=0.87),
        ),
        migrations.AlterField(
            model_name='view',
            name='uncertainty',
            field=models.FloatField(default=0.05),
        ),
    ]
