# Generated by Django 4.2 on 2023-05-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='private_acceptance_thresh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='view',
            name='public_compliance_thresh',
            field=models.FloatField(),
        ),
    ]
