# Generated by Django 4.2 on 2023-08-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectofdiscussion',
            name='opinion',
            field=models.FloatField(default=0.43),
        ),
        migrations.AlterField(
            model_name='view',
            name='attitude',
            field=models.FloatField(default=0.84),
        ),
        migrations.AlterField(
            model_name='view',
            name='opinion',
            field=models.FloatField(default=-0.7),
        ),
        migrations.AlterField(
            model_name='view',
            name='private_acceptance_thresh',
            field=models.FloatField(default=0.27),
        ),
        migrations.AlterField(
            model_name='view',
            name='uncertainty',
            field=models.FloatField(default=0.42),
        ),
    ]
