# Generated by Django 4.2 on 2023-08-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0002_alter_objectofdiscussion_opinion_alter_view_attitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectofdiscussion',
            name='opinion',
            field=models.FloatField(default=0.16),
        ),
        migrations.AlterField(
            model_name='view',
            name='attitude',
            field=models.FloatField(default=0.51),
        ),
        migrations.AlterField(
            model_name='view',
            name='opinion',
            field=models.FloatField(default=0.46),
        ),
        migrations.AlterField(
            model_name='view',
            name='private_acceptance_thresh',
            field=models.FloatField(default=0.77),
        ),
        migrations.AlterField(
            model_name='view',
            name='uncertainty',
            field=models.FloatField(default=0.12),
        ),
    ]
