# Generated by Django 4.2 on 2023-05-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0003_alter_simulation_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='simRun',
            new_name='run',
        ),
    ]
