# Generated by Django 4.2 on 2023-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0008_alter_agent_options_alter_run_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='output',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
