# Generated by Django 4.2 on 2023-07-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0009_action_status_alter_action_data_alter_action_output'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='action',
            name='status',
        ),
        migrations.AddField(
            model_name='topic',
            name='simulation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Lyra.simulation'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('simulation', 'title')},
        ),
    ]
