# Generated by Django 4.2 on 2023-07-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0010_alter_topic_options_remove_action_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='RunAction',
        ),
        migrations.CreateModel(
            name='SimAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_type', models.CharField(max_length=50)),
                ('data', models.JSONField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.run')),
            ],
        ),
    ]
