# Generated by Django 4.2 on 2023-07-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0011_rename_action_runaction_simaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simaction',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.simulation'),
        ),
    ]
