# Generated by Django 4.2 on 2023-07-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0012_alter_simaction_simulation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectofdiscussion',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='runaction',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='simaction',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='view',
            name='ood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='attitude',
            field=models.FloatField(default=-0.74),
        ),
        migrations.AlterField(
            model_name='view',
            name='opinion',
            field=models.FloatField(default=0.51),
        ),
        migrations.AlterField(
            model_name='view',
            name='private_acceptance_thresh',
            field=models.FloatField(default=0.93),
        ),
        migrations.AlterField(
            model_name='view',
            name='public_compliance_thresh',
            field=models.FloatField(default=0.6),
        ),
        migrations.AlterField(
            model_name='view',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='uncertainty',
            field=models.FloatField(default=0.45),
        ),
        migrations.AlterUniqueTogether(
            name='objectofdiscussion',
            unique_together={('topic', 'title')},
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.CheckConstraint(check=models.Q(('ood__isnull', False), ('topic__isnull', False), _connector='OR'), name='view_ood_or_topic_not_null'),
        ),
    ]
