# Generated by Django 4.2 on 2023-07-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0013_alter_objectofdiscussion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='attitude',
            field=models.FloatField(default=-0.54),
        ),
        migrations.AlterField(
            model_name='view',
            name='opinion',
            field=models.FloatField(default=-0.71),
        ),
        migrations.AlterField(
            model_name='view',
            name='uncertainty',
            field=models.FloatField(default=0.97),
        ),
    ]
