# Generated by Django 4.2 on 2023-07-11 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0014_alter_view_attitude_alter_view_opinion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='view',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='Lyra.agent'),
        ),
        migrations.AlterField(
            model_name='view',
            name='attitude',
            field=models.FloatField(default=0.09),
        ),
        migrations.AlterField(
            model_name='view',
            name='opinion',
            field=models.FloatField(default=0.8),
        ),
        migrations.AlterField(
            model_name='view',
            name='private_acceptance_thresh',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='view',
            name='uncertainty',
            field=models.FloatField(default=0.37),
        ),
    ]
