# Generated by Django 4.2 on 2023-07-14 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0016_alter_view_attitude_alter_view_ood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='view',
            name='view_ood_or_topic_not_null',
        ),
        migrations.RemoveField(
            model_name='view',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='view',
            name='ood',
        ),
        migrations.RemoveField(
            model_name='view',
            name='topic',
        ),
        migrations.AlterField(
            model_name='view',
            name='attitude',
            field=models.FloatField(default=0.06),
        ),
        migrations.AlterField(
            model_name='view',
            name='opinion',
            field=models.FloatField(default=0.47),
        ),
        migrations.AlterField(
            model_name='view',
            name='private_acceptance_thresh',
            field=models.FloatField(default=0.21),
        ),
        migrations.AlterField(
            model_name='view',
            name='uncertainty',
            field=models.FloatField(default=0.55),
        ),
        migrations.AddField(
            model_name='viewhistories',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.agent'),
        ),
        migrations.AddField(
            model_name='viewhistories',
            name='ood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.objectofdiscussion'),
        ),
        migrations.AddField(
            model_name='viewhistories',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyra.topic'),
        ),
        migrations.AddField(
            model_name='viewhistories',
            name='views',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='Lyra.view'),
        ),
        migrations.AddConstraint(
            model_name='viewhistories',
            constraint=models.CheckConstraint(check=models.Q(('ood__isnull', False), ('topic__isnull', False), _connector='OR'), name='view_ood_or_topic_not_null'),
        ),
    ]
