# Generated by Django 4.2 on 2023-07-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0018_rename_views_viewhistories_view_alter_view_attitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='attitude',
            field=models.FloatField(default=-0.08),
        ),
        migrations.AlterField(
            model_name='view',
            name='opinion',
            field=models.FloatField(default=0.81),
        ),
        migrations.AlterField(
            model_name='view',
            name='private_acceptance_thresh',
            field=models.FloatField(default=0.73),
        ),
        migrations.AlterField(
            model_name='view',
            name='uncertainty',
            field=models.FloatField(default=0.28),
        ),
    ]
