# Generated by Django 4.2 on 2023-07-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyra', '0019_alter_view_attitude_alter_view_opinion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='attitude',
            field=models.FloatField(default=0.72),
        ),
        migrations.AlterField(
            model_name='view',
            name='opinion',
            field=models.FloatField(default=0.9),
        ),
        migrations.AlterField(
            model_name='view',
            name='private_acceptance_thresh',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='view',
            name='uncertainty',
            field=models.FloatField(default=0.23),
        ),
    ]
